# 账号人设管理Agent的任务配置

account_info_creation_task:
  description: >
    创建和优化小红书账号基础信息：
    1. 设计吸引力强的账号名称
    2. 撰写专业且富有吸引力的简介
    3. 规划头像和背景图设计方向
    4. 设置关键标签和搜索关键词
    5. 优化账号基础信息的展示效果
  expected_output: >
    完整的账号基础信息方案，包含所有关键信息的具体建议
  agent: account_info_writer

persona_development_task:
  description: >
    构建独特的账号人设定位：
    1. 分析目标领域和竞品差异
    2. 设计独特的人设特质矩阵
    3. 制定人设故事化表达方案
    4. 规划差异化竞争策略
    5. 设计人设传播和互动策略
  expected_output: >
    详细的账号人设定位方案，包含完整的人设构建策略
  agent: unique_persona_builder
  context:
    - account_info_creation_task

content_planning_task:
  description: >
    规划账号内容发展方向：
    1. 制定主题内容框架
    2. 设计内容矩阵和选题方向
    3. 规划内容发布节奏
    4. 设计用户互动策略
    5. 制定热点结合计划
  expected_output: >
    完整的内容规划方案，包含具体的执行建议
  agent: content_direction_planner
  context:
    - account_info_creation_task
    - persona_development_task 